
resource.AddFile ("materials/models/neatdiskette/diskettemetal.vmt")
resource.AddFile ("materials/models/neatdiskette/diskettemetal.vtf")
resource.AddFile ("materials/models/neatdiskette/disketteplastic.vmt")
resource.AddFile ("materials/models/neatdiskette/disketteplastic.vtf")
resource.AddFile ("materials/models/neatdiskette/diskettestickeraest.vmt")
resource.AddFile ("materials/models/neatdiskette/diskettestickeraest.vtf")
resource.AddFile ("materials/models/neatdiskette/diskettestickerblue.vmt")
resource.AddFile ("materials/models/neatdiskette/diskettestickerblue.vtf")
resource.AddFile ("materials/models/neatdiskette/diskettestickergreen.vmt")
resource.AddFile ("materials/models/neatdiskette/diskettestickergreen.vtf")
resource.AddFile ("models/neatro/diskette.mdl")